### ISSUE TITLE
preprocessify fails as watchify transform module

### ISSUE THREAD

**Issue by chrishiestand** [evanmuller/preprocessify#2]
I'm trying to run preprocessify like so:

    gulp.task('browserify', function() {
        return gulp.src("").pipe(shell(['watchify -v -d -e ./dev/js/app.js -t preprocessify -t babelify --outfile ./dev/browserify/bundle.js']));
    });

and it's failing like so:

    /usr/local/lib/node_modules/watchify/index.js:77
            tr.on('file', function (file) {
               ^
    TypeError: undefined is not a function
        at Browserify.<anonymous> (/usr/local/lib/node_modules/watchify/index.js:77:12)
        at Browserify.emit (events.js:110:17)
        at Deps.<anonymous> (/usr/local/lib/node_modules/watchify/node_modules/browserify/index.js:364:14)
        at Deps.emit (events.js:110:17)
        at nr (/usr/local/lib/node_modules/watchify/node_modules/browserify/node_modules/module-deps/index.js:282:18)
        at onfile (/usr/local/lib/node_modules/watchify/node_modules/browserify/node_modules/resolve/lib/async.js:51:21)
        at onex (/usr/local/lib/node_modules/watchify/node_modules/browserify/node_modules/resolve/lib/async.js:93:22)
        at /usr/local/lib/node_modules/watchify/node_modules/browserify/node_modules/resolve/lib/async.js:24:18
        at FSReqWrap.oncomplete (fs.js:99:15)
    [18:22:39] 'browserify' errored after 654 ms

Am I doing something wrong? Any ideas? Thanks.

**Comment by evanmuller** [comment]
Preprocessify itself isn't a transform, it's a function that returns a transform.  I've never actually run it from the command line, I'm not sure how that would work.  Can you use the watchify API instead of shelling out?

This is how I'm using it...

```javascript
var browserifier = browserify('./src/app/scripts/main.js')
    .transform(preprocessify({
        exampleVariable: 'Example Variable Value'
    ))
    .bundle({debug: true});

```

**Comment by chrishiestand** [comment]
Oh okay, thanks. I think I just misunderstood that it could work that way. I've gotten what I wanted to work by using gulp-preprocess and putting the preprocessing into a separate gulp task.

We were using the shell command because we were having trouble getting the pure javascript version working with the rest of our gulp flow.

Thank you very much for your time and contribution to the community!

**Comment by bkonkle** [comment]
It's definitely not best practice to write transforms that way. See https://github.com/substack/node-browserify/issues/823. I'll try to work on a pull request later to fix this. Thanks for a great package, other than this! :-)
